# Generated by Django 2.1.5 on 2019-03-12 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hiphopTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackname', models.CharField(max_length=255)),
                ('trackdescription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hiphopTracks',
            },
        ),
        migrations.CreateModel(
            name='recordLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordname', models.CharField(max_length=255)),
                ('madeDate', models.DateField()),
                ('recordURL', models.URLField()),
                ('recorddescription', models.TextField()),
                ('hiphopTracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.hiphopTracks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recordLabels',
            },
        ),
    ]
