# Generated by Django 2.1.4 on 2019-03-18 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('mediatypedescription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mediatype',
            },
        ),
        migrations.CreateModel(
            name='RecordLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordname', models.CharField(max_length=255)),
                ('recorddate', models.DateField()),
                ('recordURL', models.URLField()),
                ('recorddescription', models.TextField()),
            ],
            options={
                'db_table': 'recordLabels',
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackno', models.CharField(max_length=255)),
                ('tracktitle', models.CharField(max_length=255)),
                ('trackdistributor', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('tracktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.MediaType')),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.AddField(
            model_name='recordlabels',
            name='tracks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Tracks'),
        ),
        migrations.AddField(
            model_name='recordlabels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
